### ISSUE TITLE
Compilação

### ISSUE THREAD

**Issue by mauigna06** [Patola/ebook#10]
Hola. Pude instalar "asciidoctor-pdf" con gem. Y descargue todo el directorio de GitHub, como hago para compilar el libro? que comando tengo que ejecutar y donde? Gracias!

**Comment by Patola** [comment]
Mil perdones. Sólo he visto ese relato de error ahora, estoy un poco sumido. Hay un archivo "Makefile" en el directorio, por lo que basta con ejecutar el comando "make" para compilar. Está en el README. ¿Está usando Linux o Windows?

**Comment by mauigna06** [comment]
He encontrado el build. No hay problema

El feb 4, 2018 11:53 AM, Patola <notifications@github.com> escribió:

Mil perdones. Sólo he visto ese relato de error ahora, estoy un poco sumido. Hay un archivo "Makefile" en el directorio, por lo que basta con ejecutar el comando "make" para compilar. Está en el README. ¿Está usando Linux o Windows?
