### ISSUE TITLE
Erros diversos

### ISSUE THREAD

**Issue by kauedg** [Patola/ebook#16]
#### Página 58
Erro de digitação
e e os -> e os
> Pelo contrário, nenhum negócio sobrevive de "intuições", **e e os** custos dizem o valor mínimo de renda necessário para sobrevivência,[...]

#### Página 191
Figura 123, mesma legenda da Figura 122

> Figura 122. Processo de calibração de uma delta (Rostock) usando uma caneta para achar o problema.https://www.youtube.com/watch?v=zElA76ncTfc  

> Figura 123. Processo de calibração de uma delta (Rostock) usando uma caneta para achar o problema.https://www.youtube.com/watch?v=zElA76ncTfc

#### Página 228 
Concordância
aquela mesmo -> aquela mesma (se refere a "propriedade do PLA")
> Por exemplo, por que não aproveitar a propriedade do PLA de baixo ponto de transição vítrea, **aquela mesmo**  que  o  torna  inapropriado  para  contato  com  alimentos  devido  a  deformar  no  lava-louças?

#### Página 239
Figura 151, mesma legenda da Figura 150

> Figura 150. Copo de PETG impresso, ao lado de uma garrafa PET de refrigerante. Note-se que a peça éapenas decorativa, não se recomenda imprimir itens com fins alimentícios em impressoras 3D comuns.  

> Figura 151. Copo de PETG impresso, ao lado de uma garrafa PET de refrigerante. Note-se que a peça éapenas decorativa, não se recomenda imprimir itens com fins alimentícios em impressoras 3D comuns.

#### Pagina 266
Erro de digitação
depresso -> depressor
>O  clorofórmio  é  um  **depresso**  do  sistema  nervoso  central, [...]

**Comment by RafaelEstevamReis** [comment]
Exceto as legendas, eu já separei as correções de grafia, vou fazer um PR

**Comment by RafaelEstevamReis** [comment]
A legenda "da Página 191"
Está em: https://github.com/Patola/ebook/blob/master/guia-maker-da-impressao-3d-tecnologiafff.adoc#L3337

**Comment by RafaelEstevamReis** [comment]
A legenda "da Página 239"
Está em: https://github.com/Patola/ebook/blob/master/guia-maker-da-impressao-3d-materiaisfff.adoc#L1236

**Comment by farribeiro** [comment]
Foi então parcialmente corrigido essa issue?

**Comment by RafaelEstevamReis** [comment]
Correto, 
Porém faltam as trocas de legenda, porém eu não sei qual eram os links que deveriam estar ali

**Comment by Patola** [comment]
Putz, eu tenho que pegar um tempo pra ver esse lance das legendas. É só a da figura 122 ou 123, certo?

**Comment by farribeiro** [comment]
> Putz, eu tenho que pegar um tempo pra ver esse lance das legendas. É só a da figura 122 ou 123, certo?

Da 150 e 151 também, @Patola

**Comment by Patola** [comment]
Vou tentar rever isso esse final de semana. Se possível me lembra lá no Telegram.

**Comment by Patola** [comment]
Legendas consertadas. Com isso, vou fechar o bug report. Obrigado, @kauedg @RafaelEstevamReis @farribeiro. @kauedg, quando for relatar bugs, ao invés de referenciar páginas do render PDF, procure referenciar a seção no livro, fica mais fácil.
