### ISSUE TITLE
Mal uso de sintaxe asciidoc

### ISSUE THREAD

**Issue by vinipsmaker** [Patola/ebook#7]
Na seção [alimentação no firmware — PWM e PID](https://github.com/Patola/ebook/blob/7e62fffacb222edba22c180efaaea7af440ed618/guia-maker-da-impressao-3d-tecnologiafff.adoc#alimenta%C3%A7%C3%A3o-no-firmwarepwm-e-pid), tem o seguinte trecho:

> Esse raciocínio de ir "suavizando" os pulsos prevendo a resposta da curva de temperatura de modo a conseguir o menor "erro" possível é o que deu origem ao algoritmo chamado de PID, sigla que descreve as três operações que usa, cada uma contribuindo e sendo somada às outras: Proporcional, Integral e Derivada. Um "controlador PID" continuamente calcula um valor de erro *e* que é a diferença entre uma medida-alvo (a temperatura desejada) e um valor medido (a temperatura atual) e a partir delas aplica uma correção baseada no histórico recente desta curva, levando em conta, com pesos específicos, a proporcional, a integral e a derivada deste erro.

Comparando com a versão do PDF antigo, vi que nele, era `e`, e não `*e*`. Olhando o código-fonte, notei que você usou `_*e*_` em vez de `__**e**__` (como utilizado em outros locais do texto).

**Comment by Patola** [comment]
Obrigado. Vou consertar. Na verdade o conversor de word pra asciidoc inicial que zoou a uniformidade dessas tags. Consertei muitas mas imaginava mesmo que não todas.
