### ISSUE TITLE
Doação Paypal com erro na página MakerLinux

### ISSUE THREAD

**Issue by BrnLng** [Patola/ebook#9]
tentei, mas retornou "We were unable to decrypt the certificate id."

**Comment by Patola** [comment]
Consertado. Desculpe demorar tanto tempo. O prejuízo é meu de qualquer jeito. :-(

**Comment by farribeiro** [comment]
Amigo @Patola , utilize gatilhos do github para fazer fechamentos de issues correlatas

No commit você escreve, por exemplo, `Closes #9`
